#!/bin/sh

# log
# Write a status message to the log.
#
# Parameters:
#   $1: The message to write.
log() {
	echo "$1" >&3
}

# dry_run
# Write a debug message to the log. Use instead of a destructive operation when
# DRY_RUN is set.
#
# Parameters:
#   $1: The message to write.
dry_run() {
	if test -n "$DRY_RUN" ; then
		echo "DRY_RUN: ${1}" >&3
	fi
}

# fatal
# Exits the script after writing an error message to the log.
#
# Parameters:
#   $1: A string describing the error encountered.
fatal() {
	echo "FAILURE in ${_IMAGE_PATH}/imager.sh: ${1}" | tee -a /etc/motd >&3
	exit 1;
}

# mtd_lookup
# Converts an MTD partition name into a device name of the form "mtdX".
#
# Parameters:
#   $1: The name of the MTD partition.
# Returns: Prints the device name.
mtd_lookup() {
	_LOOKUP_RESULT="$(tail -n '+1' '/proc/mtd' | grep -e '"'"$1"'"$' | cut -d ':' -f 1)"
	if test -z "$_LOOKUP_RESULT" ; then
		log "Failed to look up MTD partition ${1}"
		return 1
	else
		echo "$_LOOKUP_RESULT"
	fi
}

# flash_mtd_partition
# Writes an image to an MTD partition.
#
# Parameters:
#   $1: The name (NOT number) of the MTD partition to flash.
#   $2: The path to an image file to flash.
# Returns: 0 on success, 1 on failure.
flash_mtd_partition() {
	_PARTITION="$(mtd_lookup "$1")"
	if test "$?" -ne 0 ; then
		return 1;
	fi

	log "Flashing ${2} to ${1} (${_PARTITION})"
	dry_run "Skipping flash on dry run"
	if test -z "$DRY_RUN" ; then
		flash_erase -q "/dev/${_PARTITION}" 0 0 &&
		nandwrite -qp "/dev/${_PARTITION}" "$2"
	fi
}

# mount_mtd_partition
# Mounts an MTD partition to a temporary directory.
#
# Parameters:
#   $1: The name (NOT number) of the MTD partition to mount.
# Returns: Prints the path to a mounted temporary directory.
mount_mtd_partition() {
	_PARTITION="$(mtd_lookup "$1")"
	if test "$?" -ne 0 ; then
		return 1;
	fi

	_MOUNT_DIR="$(mktemp -d)"
	log "Mounting ${1} (${_PARTITION}) at ${_MOUNT_DIR}"
	if ! mount "/dev/mtdblock${_PARTITION#mtd}" "$_MOUNT_DIR" ; then
		log "Could not mount MTD partition ${1}"
		return 1;
	fi
	echo "$_MOUNT_DIR"
}

# cleanup_mount
# Unmounts and cleans up a directory mounted using a mount_* helper.
#
# Parameters:
#   $1: The path of the mount to clean up.
cleanup_mount() {
	log "Unmounting ${1}"
	umount "$1"
	rmdir "$1"
}

# clear_data
# Empties all stock files from the data partition.
_CLEAR_DATA_SKIP='. .. lost+found flashcast'
clear_data() {
	_DATA="$(mount_mtd_partition userdata)"
	log "Clearing userdata partition (${_DATA})"
	ls -a "$_DATA" | while read _PATH ; do
		for _I in $_CLEAR_DATA_SKIP ; do
			if test "$_PATH" = "$_I" ; then
				continue 2
			fi
		done

		dry_run "Would remove ${_DATA}/${_PATH}"
		if test -z "$DRY_RUN" ; then
			rm -rf "${_DATA}/${_PATH}"
		fi
	done
	cleanup_mount "$_DATA"
}

# begin_squashfs_edit
# Mounts a read-only squashfs partition in such a way that it can be modified
# and the changes stored in RAM. Be sure to call end_squashfs_edit when you're
# done to flash the edited filesystem back. NOTE: Due to limitations in the
# provided kernel source, this function can currently only be used with the
# "rootfs" MTD partition.
#
# Parameters:
#   $1: The name (NOT number) of the MTD partition to mount.
# Returns: Prints the path to the editable mount.
begin_squashfs_edit() {
	if test "$1" != 'rootfs' ; then
		log "begin_squashfs_edit can only be used with the rootfs MTD partition"
		return 1;
	fi

	_WRAPPER="$(mktemp -d)"
	log "Setting up squashfs union at ${_WRAPPER}"
	mkdir "${_WRAPPER}/base" "${_WRAPPER}/overlay" "${_WRAPPER}/union"

	_PARTITION="$(mtd_lookup "$1")"
	if test "$?" -ne 0 ; then
		return 1;
	fi
	if ! mount -t squashfs "/dev/mtdblock${_PARTITION#mtd}" "${_WRAPPER}/base" ; then
		log "Could not mount MTD partition ${1}"
		return 1;
	fi

	unionfs -o cow "${_WRAPPER}/overlay=RW:${_WRAPPER}/base=RO" "${_WRAPPER}/union"

	echo "$1" > "${_WRAPPER}/mtdpart"
	echo "${_WRAPPER}/union"
}

# begin_squashfs_image_edit
# Mounts a local squashfs image file to be edited and then written to disk with
# end_squashfs_edit.
#
# Parameters:
#   $1: The path of the local squashfs image.
#   $2: The name (NOT number) of the MTD partition to write the image to.
# Returns: Prints the path to the editable mount.
begin_squashfs_image_edit() {
	_WRAPPER="$(mktemp -d)"
	log "Setting up squashfs image union at ${_WRAPPER}"
	mkdir "${_WRAPPER}/base" "${_WRAPPER}/overlay" "${_WRAPPER}/union"

	if ! mount -o loop -t squashfs "$1" "${_WRAPPER}/base" ; then
		log "Could not mount local squashfs image ${1}"
		return 1
	fi

	unionfs -o cow "${_WRAPPER}/overlay=RW:${_WRAPPER}/base=RO" "${_WRAPPER}/union"

	echo "$2" > "${_WRAPPER}/mtdpart"
	echo "${_WRAPPER}/union"
}

# end_squashfs_edit
# Reflashes a squashfs from a previously-edited partition and cleans up the
# mount points.
#
# Parameters:
#   $1: The directory returned by begin_squashfs_edit.
end_squashfs_edit() {
	_WRAPPER="${1%/union}"
	log "Reflashing squashfs union at ${_WRAPPER}"

	_REPACKED_FS="${_WRAPPER}/repack.sqfs"
	if ! mksquashfs "${_WRAPPER}/union" "$_REPACKED_FS" -no-progress ; then
		log "Failed to repack squashfs image at ${_WRAPPER}"
		return 1
	fi

	flash_mtd_partition "$(cat "${_WRAPPER}/mtdpart")" "${_WRAPPER}/repack.sqfs"

	fusermount -u "${_WRAPPER}/union"
	umount "${_WRAPPER}/base"

	rm -rf "${_WRAPPER}"
}

# Put the mod in a temp directory.
if test -f "$1" -a "${1%.zip}" != "$1" ; then
	_IMAGE_PATH="$(mktemp -d)"
	echo "Extracting ${1} (zip) to ${_IMAGE_PATH}"

	unzip -d "$_IMAGE_PATH" "$1"
elif test -f "$1" -a "${1%.tar*}" != "$1" ; then
	_IMAGE_PATH="$(mktemp -d)"
	echo "Extracting ${1} (tar) to ${_IMAGE_PATH}"

	tar -xv -C "$_IMAGE_PATH" -f "$1"
elif test -d "$1" ; then
	_IMAGE_PATH="$(mktemp -u)"
	echo "Copying ${1} to ${_IMAGE_PATH}"

	cp -r "$1" "$_IMAGE_PATH"
	chmod 755 "$_IMAGE_PATH"
else
	echo "${1} is not of a recognized mod format"
	exit 0
fi

# Make sure to clean up when we're done.
_ORIG_PWD="$(pwd)"
_clean_up() {
	echo "Removing temporary mod directory ${_IMAGE_PATH}"
	cd "$_ORIG_PWD"
	rm -rf "$_IMAGE_PATH"
}

# Check for and run the imager script.
echo "Flashing mod at ${_IMAGE_PATH}"
trap _clean_up EXIT
cd "$_IMAGE_PATH"

if ! test -f './imager.sh' ; then
	echo "ERROR: $(pwd)/imager.sh does not exist"
	exit 1
fi

shift
source './imager.sh' "$@" 3>&1
