#!/bin/sh
#
# Sets the HDMI resolution for DirectFB.
#

case "$1" in
  start)
	echo -n "Setting resolution"
	/usr/bin/res-shim
	;;
  stop)
	exit 1
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 1
esac

exit $?