#!/bin/sh
#
# Starts dropbear sshd.
#

# Make sure the dropbearkey progam exists
[ -f /usr/bin/dropbearkey ] || exit 0

start() {
 	echo -n "Starting dropbear sshd: "

	# Mount userdata so we have persistent keys
	DATA="$(mktemp -d)"
	if ! mount /dev/mtdblock5 "$DATA" ; then
		rmdir "$DATA"
		exit 1
	fi

	# Make sure dropbear directory exists
	if [ ! -d "${DATA}/flashcast/dropbear" ] ; then
		mkdir -p "${DATA}/flashcast/dropbear"
	fi
	# Check for the Dropbear RSA key
	if [ ! -f "${DATA}/flashcast/dropbear/dropbear_rsa_host_key" ] ; then
		echo -n "generating rsa key... "
		/usr/bin/dropbearkey -t rsa -f "${DATA}/flashcast/dropbear/dropbear_rsa_host_key" > /dev/null 2>&1
	fi

	# Check for the Dropbear DSS key
	if [ ! -f "${DATA}/flashcast/dropbear/dropbear_dss_host_key" ] ; then
		echo -n "generating dsa key... "
		/usr/bin/dropbearkey -t dss -f "${DATA}/flashcast/dropbear/dropbear_dss_host_key" > /dev/null 2>&1
	fi
	umask 077
	start-stop-daemon -S -q -p /var/run/dropbear.pid --exec /usr/sbin/dropbear -- -r "${DATA}/flashcast/dropbear/dropbear_rsa_host_key" -d "${DATA}/flashcast/dropbear/dropbear_dss_host_key"
	umount "$DATA"
	rmdir "$DATA"
	echo "OK"
}
stop() {
	echo -n "Stopping dropbear sshd: "
	start-stop-daemon -K -q -p /var/run/dropbear.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

