#!/bin/sh
#
# Starts PE_Single_CPU for Berlin.
#

start() {
	echo -n "Starting PE_Single_CPU: "
	start-stop-daemon -b -S -q -x /bin/PE_Single_CPU
	echo "OK"
}
stop() {
	echo -n "Stopping PE_Single_CPU: "
	start-stop-daemon -K -q -x /bin/PE_Single_CPU
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

